# manifesto

```UNGRUND MANIFESTO

WE WRITE THIS MANIFESTO FROM UNGRUND ORIGINS. IN TECNOCAPITAL ACCELERATION
INTENSITIES/ATTENTIONS MUST BE ACTIVELY TRANSFORMED ONE MUST INVOKE ALL AT ONCE
SPECTRUMS COMES TO CONSTITUTE DISCOURSES, EPISTEMES, THERE BEING NO TIME IF NOT
FOR THE TRANSMISSION OF TRUTH, HEARING THE NOISE OF IT'S STRONGEST OPPOSITION.

DECENTRALIZED COMMUNITIES MUST BE BUILT IN COLLABORATION WITH SOCIAL TECHNOLOGIES 
AS WITH UNIVERSITIES, TELECOMMUNICATIONAL AND HEALTH SCIENCE CENTERS. DECISIONS MUST BE
PUBLIC AND OPEN TO DISCUSSION, WHERE THE INSTITUTIONAL PARADOX OF REGISTRIES, PROPERTIES, 
SIGNS, BECOMES INFIMUS WHILE DEALING WITH IT'S INFINITY AND REPRODUCIBILITY.

ENABLING THE DEMYSTIFICATION OF SCIENCES WITH OPEN KNOWLEDGE, OPEN DISCOURSE, OPEN
EXPRESSIVITIES. SUCH TRANSMISSION WOULD BE DISTRIBUTED, OPERATING ON (PERCEPTORIAL) CHANNELS.

EACH MUST HAVE THE RIGHT TO EXCHANGE INTENSITIES, PROPERTIES -- WHICH ARE UNNALIENABLE.
POSSIBILITIES OF SETTLING PROPERTIES MUST REMAIN OPEN IN IT'S UNKOWN HORIZONS, 
SUBVERTING SUCH CONCEPT AS A PREMISE FOR HANDLING CONTIGENCIES. UNKNOWN WORLS ON EARTH
MUST BE RESPECTED TAKING INTO ACCOUNT A PRINCIPLE OF UNDECIDILITY.

IN SUCH SENSE UNGRUND ORACLE WOULD EMANCIPATE UNKNOWN VOICES WITH A MYRIAD OF PATHS,
OF PATCHWORKS WHICH COMES TO BE.

@SMARTKONTRAKT NOV 2020
```

https://ipfs.io/ipfs/QmT54nWdcvfAg9ByPwUiMPtqHKU8uK8XMw8zwb7NaXy51m 
```
KT1M2Gng6zuDEy7PFivXPDYgrNnYEfLsc1z1#13
```
