import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  teiaSidebar: [
    {
      type: 'category',
      label: 'General',
      items: [
        // 'home',
        'core-values-code-of-conduct-terms-and-conditions',
        'governance-on-teia',
        'core-team',
        'user-safety',
      ],
    },
    {
      type: 'category',
      label: 'Copyright, Moderation, Restrictions',
      items: [
        {
          type: 'link',
          label: 'Report Harassment or Scams',
          href: 'https://docs.google.com/forms/d/e/1FAIpQLSeuBmNJjTiROSbHXXiQ5e-ia6fFywHKZ7Dj4-7sZtyltGY3yA/viewform',
        },
        {
          type: 'link',
          label: 'Account restrictions / Rules (report abuse/request unban)',
          href: '/core-values-code-of-conduct-terms-and-conditions#content-moderation',
        },
        'copyright-and-license-guide',
        'collecting-nfts-safely',
      ],
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started',
        },

      ],
    },
    {
      type: 'category',
      label: 'How-Tos',
      items: [
        {
          type: 'autogenerated',
          dirName: 'howtos',
        },
      ],
    },
    {
      type: 'category',
      label: 'Dev How-Tos',
      items: [
        {
          type: 'autogenerated',
          dirName: 'dev-howtos',
        },
      ],
    },
    {
      type: 'category',
      label: 'FAQs',
      items: [
        {
          type: 'autogenerated',
          dirName: 'faqs',
        },
      ],
    },
    {
      type: 'category',
      label: 'Charity Initiatives',
      items: [
        {
          type: 'autogenerated',
          dirName: 'charity',
        },
        {
          type: 'link',
          label: 'How to set split sale swaps on objkt.com',
          href: '/howtos/collab-contract-guide#setting-up-a-contract-for-fundraisers',
        },
      ],
    },
    {
      type: 'category',
      label: 'Resources/Lists',
      items: [
        {
          type: 'autogenerated',
          dirName: 'resources',
        },
      ],
    },
  ],
};

export default sidebars;
